#!/usr/bin/env python

import os
Import('env')
dirs = [".", "libqhullcpp/", "libqhull_r/"]

src_list = []
for direc in dirs:
	for file in os.listdir(direc):
		if direc == ".":
			direc = ""
		if file.endswith('.cpp') or file.endswith('.c'):
			src_list.append(direc + file)

module_env = env.Clone()
module_env.add_source_files(env.modules_sources, src_list)
module_env.Append(CXXFLAGS=['-std=c++11'])



